import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import QueryProvider from '@/providers/query-provider';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
	return (
		<html lang="en">
		<body
			className={cn(
				inter.className,
				'min-h-screen bg-background antialiased',
			)}
		>
		<QueryProvider>
			{children}
		</QueryProvider>
		</body>
		</html>
	);
};

export default RootLayout;
