name: Ticker Pipeline

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - '**'

env:
  IMAGE: ghcr.io/arthurdotwork/dreamtrader/ticker

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: ./deploy.sh ${{ env.IMAGE }} -f Dockerfile
        working-directory: apps/ticker
